# Generated by Django 5.1.1 on 2024-11-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='road_name',
        ),
    ]
