# Generated by Django 5.1.1 on 2024-11-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0007_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ReferralCode',
        ),
    ]
