# Generated by Django 5.1.1 on 2024-11-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0013_user_points_referralpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.DeleteModel(
            name='ReferralPoints',
        ),
    ]
