# Generated by Django 5.1.1 on 2024-11-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0014_remove_user_points_delete_referralpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='points_awarded',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
