# Generated by Django 5.1.1 on 2024-11-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0015_referral_points_awarded_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='points_awarded',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
