# Generated by Django 5.1.1 on 2024-11-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0017_coinpurchase_referralpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralpoints',
            name='referred_user',
        ),
        migrations.DeleteModel(
            name='CoinPurchase',
        ),
        migrations.DeleteModel(
            name='ReferralPoints',
        ),
    ]
