# Generated by Django 5.1.1 on 2024-11-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0019_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
