# Generated by Django 5.1.1 on 2024-11-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0021_user_points_coinpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.DeleteModel(
            name='CoinPurchase',
        ),
    ]
