# Generated by Django 5.1.1 on 2024-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0023_user_points_coinpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinpurchase',
            name='number_of_coins',
            field=models.PositiveIntegerField(),
        ),
    ]
