# Generated by Django 5.1.1 on 2024-11-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0025_room_alter_user_points_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
