# Generated by Django 5.1.1 on 2024-11-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0027_hotel_hotelbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
