# Generated by Django 5.1.1 on 2024-11-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0029_hotelbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='user',
            new_name='name',
        ),
    ]
