# Generated by Django 5.1.1 on 2024-11-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0030_rename_user_hotelbooking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='price_per',
            new_name='price_per_night',
        ),
    ]
