# Generated by Django 5.1.1 on 2024-11-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0031_rename_price_per_hotel_price_per_night'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='price_per_night',
            new_name='price_per',
        ),
    ]
