# Generated by Django 5.1.1 on 2024-11-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0033_rename_name_hotelbooking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
