# Generated by Django 5.1.1 on 2024-11-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0036_hotelbooking_delete_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='user',
            new_name='name',
        ),
    ]
