# Generated by Django 5.1.1 on 2024-11-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0038_alter_hotelbooking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
