# Generated by Django 5.1.1 on 2024-11-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0041_alter_hotel_name_roomtype_hotel_room_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='hotelroom_name',
            field=models.CharField(max_length=255),
        ),
    ]
