# Generated by Django 5.1.1 on 2024-11-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0041_roomtype_hotelbooking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='room_types',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='coinapp.roomtype'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types_list', to='coinapp.hotel'),
        ),
    ]
