# Generated by Django 5.1.1 on 2024-11-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0042_alter_roomtype_hotelroom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='hotelroom_name',
            new_name='room_name',
        ),
    ]
