# Generated by Django 5.1.1 on 2024-11-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0042_hotel_room_types_alter_roomtype_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
