# Generated by Django 5.1.1 on 2024-11-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0045_alter_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_in_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
