# Generated by Django 5.1.1 on 2024-11-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0046_hotel_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='check_in_date',
            field=models.DateField(),
        ),
    ]
