# Generated by Django 5.1.1 on 2024-11-12 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0047_alter_hotel_check_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
