# Generated by Django 5.1.1 on 2024-11-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0050_roomavailability_room_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomavailability',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinapp.roomtype'),
        ),
    ]
