# Generated by Django 5.1.1 on 2024-11-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0051_alter_roomavailability_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomavailability',
            name='room_type',
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomavailability',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomavailabilities', to='coinapp.hotel'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types_list', to='coinapp.hotel'),
        ),
    ]
