# Generated by Django 5.1.1 on 2024-11-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0054_hotelbooking_check_out_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='check_out_date',
        ),
    ]
